### ISSUE TITLE
ImportError: cannot import name 'Connection' from 'rq'

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#4684]
https://community-tc.services.mozilla.com/tasks/E3nF2kQaQGa92-1-perv7Q/runs/0/logs/public/logs/live.log#L12352:
```
  File "/usr/local/bin/bugbug-http-worker", line 5, in <module>
    from bugbug_http.worker import main
  File "/usr/local/lib/python3.12/site-packages/bugbug_http/worker.py", line 12, in <module>
    from rq import Connection, Worker
ImportError: cannot import name 'Connection' from 'rq' (/usr/local/lib/python3.12/site-packages/rq/__init__.py). Did you mean: 'connections'?
```

**Comment by suhaibmujahid** [comment]
This regressed by https://github.com/mozilla/bugbug/pull/4601
