### ISSUE TITLE
AttributeError: 'super' object has no attribute '__sklearn_tags__'

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#4730]
https://community-tc.services.mozilla.com/tasks/KoxvuXklS6qjvZcOytJGiw/runs/0/logs/public/logs/live.log#L1381:

```
  /usr/local/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
  Traceback (most recent call last):
    File "/usr/local/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
      score = scorer._score(
              ^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 380, in _score
      y_pred = method_caller(
               ^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
      result, _ = _get_response_values(
                  ^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/sklearn/utils/_response.py", line 242, in _get_response_values
      y_pred, pos_label = prediction_method(X), None
                          ^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/imblearn/pipeline.py", line 653, in predict
      with _raise_or_warn_if_not_fitted(self):
    File "/usr/local/lib/python3.12/contextlib.py", line 144, in __exit__
      next(self.gen)
    File "/usr/local/lib/python3.12/site-packages/imblearn/pipeline.py", line 63, in _raise_or_warn_if_not_fitted
      check_is_fitted(estimator)
    File "/usr/local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1756, in check_is_fitted
      if not _is_fitted(estimator, attributes, all_or_any):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1665, in _is_fitted
      return estimator.__sklearn_is_fitted__()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/imblearn/pipeline.py", line 1297, in __sklearn_is_fitted__
      check_is_fitted(last_step)
    File "/usr/local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1751, in check_is_fitted
      tags = get_tags(estimator)
             ^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/sklearn/utils/_tags.py", line 405, in get_tags
      sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/sklearn/base.py", line 540, in __sklearn_tags__
      tags = super().__sklearn_tags__()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: 'super' object has no attribute '__sklearn_tags__'
```

This seems to be regressed by https://github.com/mozilla/bugbug/pull/4709

**Comment by suhaibmujahid** [comment]
> Could this be caused by the version of `scikit-learn`? As mentioned in the discussion [here](https://stackoverflow.com/questions/79290968/super-object-has-no-attribute-sklearn-tags)

But it seems to be fixed when downgrading imbalanced-learn.

**Comment by benjaminmah** [comment]
> But it seems to be fixed when downgrading imbalanced-learn.

Yes, but wouldn't that mean it's dependent on imbalanced-learn itself? In the discussion, similar solutions were mentioned via upgrading XGBoost or downgrading scikit-learn.

**Comment by suhaibmujahid** [comment]
The downgrading imbalanced-learn fixed it for `bugbug tests`, but now I see the same error in [`bugbug integration test`](https://community-tc.services.mozilla.com/tasks/Wj7OlWhLSeKcuJeobgYHtg/runs/0/logs/live/public/logs/live.log#L24596):
```
/usr/local/lib/python3.12/site-packages/sklearn/utils/_tags.py:354: FutureWarning: The XGBClassifier or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(
2025-01-14 18:37:25,916:ERROR:rq.worker:[Job 9b3517c5e4f548cdbcf28930b57173b2]: exception raised while executing (bugbug_http.models.classify_bug)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
                   ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bugbug_http/models.py", line 92, in classify_bug
    model = MODEL_CACHE.get(model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bugbug_http/readthrough_cache.py", line 40, in get
    item = self.load_item_function(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bugbug_http/models.py", line 56, in <lambda>
    timedelta(hours=1), lambda m: Model.load(f"{m}model")
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bugbug/model.py", line 621, in load
    model.clf.named_steps["estimator"].load_model(xgboost_model_path)
  File "/usr/local/lib/python3.12/site-packages/xgboost/sklearn.py", line 930, in load_model
    self._load_model_attributes(config)
  File "/usr/local/lib/python3.12/site-packages/xgboost/sklearn.py", line 945, in _load_model_attributes
    if is_classifier(self):
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sklearn/base.py", line 1237, in is_classifier
    return get_tags(estimator).estimator_type == "classifier"
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sklearn/utils/_tags.py", line 405, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sklearn/base.py", line 540, in __sklearn_tags__
    tags = super().__sklearn_tags__()
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute '__sklearn_tags__'
```
