### PR TITLE
Fix tests

### LINKED ISSUE #6587: Test failures due to not providing the agent name in the context
Regressed by https://github.com/mozilla/bugbug/pull/6584
```
=========================== short test summary info ============================
FAILED tests/test_try_server_handler.py::test_apply_appends_the_config_commit_to_the_agents_patches - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_returns_treeherder_and_lando_urls - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_fails_without_a_patch_artifact - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_fails_without_any_selection - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_pushes_an_auto_selection_without_task_labels - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_carries_resolved_test_paths_into_the_config - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_reports_a_missing_lando_token - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_reports_a_lando_rejection - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
=================== 8 failed, 245 passed, 1 warning in 7.33s ===================
```

### PR DESCRIPTION
**Pull request by evgenyrp**
fixes #6587

### CODE REVIEW

**Comment by evgenyrp** [comment]
It seems there's an issue with Taskcluster:

```
taskcluster_yml..........................................................Failed
- hook id: taskcluster_yml
- exit code: 1
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repo99ho1xx2/py_env-python3.12/lib/python3.12/site-packages/referencing/_core.py", line 428, in get_or_retrieve
    resource = registry._retrieve(uri)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pre-commit/repo99ho1xx2/py_env-python3.12/lib/python3.12/site-packages/jsonschema/validators.py", line 113, in _warn_for_remote_retrieve
    with urlopen(request) as response:  # noqa: S310
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

```

**Comment by evgenyrp** [comment]
Restarted the task, it passed now.

**Review by suhaibmujahid — APPROVED** [review]
Thank you!
