### ISSUE TITLE
Test failures due to not providing the agent name in the context

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#6587]
Regressed by https://github.com/mozilla/bugbug/pull/6584
```
=========================== short test summary info ============================
FAILED tests/test_try_server_handler.py::test_apply_appends_the_config_commit_to_the_agents_patches - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_returns_treeherder_and_lando_urls - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_fails_without_a_patch_artifact - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_fails_without_any_selection - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_pushes_an_auto_selection_without_task_labels - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_carries_resolved_test_paths_into_the_config - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_reports_a_missing_lando_token - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
FAILED tests/test_try_server_handler.py::test_apply_reports_a_lando_rejection - TypeError: ApplyContext.__init__() missing 1 required positional argument: ...
=================== 8 failed, 245 passed, 1 warning in 7.33s ===================
```
