### ISSUE TITLE
Add scikit-image==0.14.2 as requirement

### ISSUE THREAD

**Issue by sbeesm** [mozilla/bugbug#120]
scikit-image<=0.14.1 is incompatible with numpy>=1.16.0.

`_validate_lengths` was removed in numpy 1.16.0. To handle deprecation scikit-image 0.14.2 should be used.

Using numpy<1.16.0 is also not an option as `_multiarray_umath` is new to numpy 1.16.0 and not there in previous versions.

**Comment by marco-c** [comment]
I can't reproduce this locally, and it can't be reproduced on Travis. Maybe it was a problem with your local environment?

**Comment by sbeesm** [comment]
Initially I was using scikit-image 0.14.1, so when I ran the `run.py` script, this error occured:

`ImportError: cannot import name '_validate_lengths'`

But the problem is solved after updating it to 0.14.2.

**Comment by marco-c** [comment]
So it was a problem in your local configuration.
